# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Pirate Party of Canada
tagline:          'Evidence Based Policy Making'
description:      'Evidence based policy making focusing on progressive values.'
url:              http://pirateparty.ca

author:
  name:           'Pirate Party of Canada'
  url:            https://twitter.com/piratepartyca

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/piratepartyca/piratepartyca.github.io